// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdyqednkaxsdmfzjlxbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkeXFlZG5rYXhzZG1mempseGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzYxMTUsImV4cCI6MjA2MTQxMjExNX0.reODUmNGlbketmZxg0oCEnNPiCT9Jy1MM4ug43vw0cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);